Repository Nik-Potokar/XIVSlothCombo, pull requests merged in 2022-05, with the labels that each got.

#622 [RPRPvP] Burst Mode & Options
  XIVSlothCombo/CombosPVP/RPRPVP.cs
  XIVSlothCombo/ConfigWindow.cs
  XIVSlothCombo/CustomComboPreset.cs
Labels: Feature

#666 [DNC] Features & Fixes
  XIVSlothCombo/Combos/DNC.cs
  XIVSlothCombo/ConfigWindow.cs
  XIVSlothCombo/CustomComboPreset.cs
Labels: Enhancement, Feature, In Progress

#672 [DNC] Simple Step Fill Options
  XIVSlothCombo/Combos/DNC.cs
  XIVSlothCombo/CustomComboPreset.cs
Labels: Feature, In Progress

#667 SCH & SGE Discord Feedback
  XIVSlothCombo/Combos/SCH.cs
  XIVSlothCombo/Combos/SGE.cs
  XIVSlothCombo/ConfigWindow.cs
  XIVSlothCombo/CustomComboPreset.cs
Labels: Consideration Needed, In Progress

#715 Feature name formatting
  XIVSlothCombo/Attributes/CustomComboInfoAttribute.cs
  XIVSlothCombo/Combos/BLU.cs
  XIVSlothCombo/Combos/BRD.cs
  XIVSlothCombo/Combos/DNC.cs
  XIVSlothCombo/Combos/DOL.cs
  XIVSlothCombo/ConfigWindow.cs
  XIVSlothCombo/CustomCombo.cs
  XIVSlothCombo/CustomComboPreset.cs
Labels: Documentation, In Progress

#719 [NIN] Level check hotfix + Formatting
  XIVSlothCombo/Combos/NIN.cs
Labels: Bug, In Progress
