Repository Nik-Potokar/XIVSlothCombo, pull requests merged in 2022-11, with the labels that each got.

#1053 [Framework] Upgraded InActionRange for Radius math of Self Targetting actions
  XIVSlothCombo/CustomCombo/Functions/Action.cs
  XIVSlothCombo/Data/ActionWatching.cs
Labels: Enhancement, Pull Request

#1062 [SGE] Add `Rhizomata Option` to ST and AoE combos
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/SGE.cs
  XIVSlothCombo/Window/Functions/UserConfig.cs
Labels: Pull Request

#1079 [RPR] SoulSow Internal fixes
  XIVSlothCombo/Combos/PvE/RPR.cs
  XIVSlothCombo/Window/Functions/UserConfig.cs
Labels: Pull Request

#1099 [GNB] Fix `No Mercy on Gnashing Fang`
  XIVSlothCombo/Combos/PvE/GNB.cs
Labels: Pull Request

#1086 Localization Tweaks to Debuff Checks
  XIVSlothCombo/CustomCombo/Functions/Status.cs
Labels: Pull Request

#1078 GNB 3.0 Rework
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/GNB.cs
  XIVSlothCombo/Window/Functions/UserConfig.cs
Labels: Pull Request

#1100 [GNB] Fixed `No Mercy on Gnashing Fang` reference
  XIVSlothCombo/Combos/PvE/GNB.cs
Labels: Pull Request

#1101 [GNB] Feature/Option naming + user config reset
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/XIVSlothCombo.cs
Labels: Pull Request

#1071 [WHM] Requested Feature: Medica Thin Air
  XIVSlothCombo/Combos/PvE/WHM.cs
  XIVSlothCombo/Window/Functions/UserConfig.cs
Labels: Pull Request

#1095 [RPR] Add option to hold one charge of True North for use with Gluttony
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/RPR.cs
Labels: Pull Request

#1058 [DNC] Adjustments and extra checks
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/DNC.cs
  XIVSlothCombo/Window/Functions/UserConfig.cs
Labels: Pull Request

#1063 [SGE] DPS Revamp
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/SGE.cs
  XIVSlothCombo/CustomCombo/Functions/Config.cs
  XIVSlothCombo/Window/Functions/UserConfig.cs
Labels: Pull Request

#1087 SCH/SGE: Healing Mouseover Electric Boogaloo + Esuna
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/SCH.cs
  XIVSlothCombo/Combos/PvE/SGE.cs
  XIVSlothCombo/CustomCombo/Functions/Status.cs
  XIVSlothCombo/CustomCombo/Functions/Target.cs
  XIVSlothCombo/Window/Functions/UserConfig.cs
Labels: Pull Request

#1075 [BLM] Aetherial Manipulation Feature
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/BLM.cs
Labels: Feature, Pull Request

#1080 [SMN] Added "Burst during Any Searing Light" option
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/SMN.cs
Labels: Pull Request

#912 [DRKPVP] Implementation of Burst Mode
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvP/DRKPVP.cs
  XIVSlothCombo/Combos/PvP/PVPCommon.cs
  XIVSlothCombo/Window/Functions/UserConfig.cs
Labels: Pull Request

#1085 [SMN] Add Energy Drain to AoE Combo if too low level to use Energy Siphon.
  XIVSlothCombo/Combos/PvE/SMN.cs
Labels: Pull Request

#1061 [SAM] Extra Kenki Utilisation in Opener
  XIVSlothCombo/Combos/PvE/SAM.cs
Labels: Pull Request

#1052 [MNK] Skill Display Fix
  XIVSlothCombo/Combos/PvE/MNK.cs
Labels: Pull Request

#1073 [MNK] Changes to the "Bootshine" replacement function
  XIVSlothCombo/Combos/PvE/MNK.cs
Labels: Pull Request

#1031 [MNK] Dynamic True North
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/MNK.cs
Labels: Pull Request

#1083 [DRK/DRG] Minor changes
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/DRG.cs
  XIVSlothCombo/Combos/PvE/DRK.cs
  XIVSlothCombo/Combos/PvE/RPR.cs
Labels: Pull Request

#1111 [MNK] Dynamic True North minor tweak
  XIVSlothCombo/Combos/PvE/MNK.cs
Labels: Pull Request

#1117 AST Simple Heal: Added SoftTarget and MO support
  XIVSlothCombo/Combos/PvE/AST.cs
  XIVSlothCombo/Window/Functions/UserConfig.cs
Labels: Pull Request

#1091 [NIN] Uptime feature adjustment + Pooling Option
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/NIN.cs
  XIVSlothCombo/Window/Functions/UserConfig.cs
Labels: Pull Request

#1106 [RPR] Further separation of burst options
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/RPR.cs
Labels: Pull Request

#1116 [DNC] Semi-rework
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/DNC.cs
  XIVSlothCombo/Window/Functions/UserConfig.cs
Labels: Pull Request

#1118 Dynamic true north ninja
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/NIN.cs
Labels: Pull Request

#1090 [ALL] Variant Ability Support
  XIVSlothCombo/Attributes/BozjaAttribute.cs
  XIVSlothCombo/Attributes/BozjaParentAttribute.cs
  XIVSlothCombo/Attributes/CustomComboInfoAttribute.cs
  XIVSlothCombo/Attributes/EurekaAttribute.cs
  XIVSlothCombo/Attributes/EurekaParentAttribute.cs
  XIVSlothCombo/Attributes/VariantAttribute.cs
  XIVSlothCombo/Attributes/VariantParentAttribute.cs
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/AST.cs
  XIVSlothCombo/Combos/PvE/BLM.cs
  XIVSlothCombo/Combos/PvE/BRD.cs
  XIVSlothCombo/Combos/PvE/DNC.cs
  XIVSlothCombo/Combos/PvE/DRG.cs
  XIVSlothCombo/Combos/PvE/DRK.cs
  XIVSlothCombo/Combos/PvE/GNB.cs
  XIVSlothCombo/Combos/PvE/MCH.cs
  XIVSlothCombo/Combos/PvE/MNK.cs
  XIVSlothCombo/Combos/PvE/NIN.cs
  XIVSlothCombo/Combos/PvE/PLD.cs
  XIVSlothCombo/Combos/PvE/RPR.cs
  XIVSlothCombo/Combos/PvE/SAM.cs
  XIVSlothCombo/Combos/PvE/SCH.cs
  XIVSlothCombo/Combos/PvE/SGE.cs
  XIVSlothCombo/Combos/PvE/SMN.cs
  XIVSlothCombo/Combos/PvE/Variant.cs
  XIVSlothCombo/Combos/PvE/WAR.cs
  XIVSlothCombo/Combos/PvE/WHM.cs
  XIVSlothCombo/Core/PluginConfiguration.cs
  XIVSlothCombo/CustomCombo/Functions/Cooldown.cs
  XIVSlothCombo/Data/CooldownData.cs
  XIVSlothCombo/Data/CustomComboCache.cs
  XIVSlothCombo/Window/ConfigWindow.cs
  XIVSlothCombo/Window/Functions/Presets.cs
  XIVSlothCombo/Window/Functions/UserConfig.cs
  XIVSlothCombo/Window/Tabs/PvEFeatures.cs
Labels: Pull Request
