Repository Nik-Potokar/XIVSlothCombo, pull requests merged in 2022-10, with the labels that each got.

#1015 Refix Phantom Change
  XIVSlothCombo/Combos/PvE/NIN.cs
Labels: Pull Request

#938 [Framework] GetLevel "Failure" Fix
  XIVSlothCombo/Data/ActionWatching.cs
Labels: Pull Request

#985 [ALL] LevelChecked/ActionReady
  XIVSlothCombo/Combos/PvE/ALL.cs
  XIVSlothCombo/Combos/PvE/RDM.cs
  XIVSlothCombo/Combos/PvE/SMN.cs
Labels: Pull Request

#1020 Bard and Samurai Combo Heal Fixes
  XIVSlothCombo/Combos/PvE/BRD.cs
  XIVSlothCombo/Combos/PvE/SAM.cs
Labels: Pull Request

#1018 Fixed Sage AoE Phlega Lucid Weaving.
  XIVSlothCombo/Combos/PvE/SGE.cs
Labels: Pull Request

#1025 [War] Add incombat check to infuriate.
  XIVSlothCombo/Combos/PvE/WAR.cs
Labels: Pull Request

#1016 [Healers] Added DoT Thresholds
  XIVSlothCombo/Combos/PvE/AST.cs
  XIVSlothCombo/Combos/PvE/SCH.cs
  XIVSlothCombo/Combos/PvE/SGE.cs
  XIVSlothCombo/Combos/PvE/WHM.cs
  XIVSlothCombo/Window/Functions/UserConfig.cs
Labels: Pull Request

#1028 [Bugfix/Framework] ActionWatching LastAction fixes for non-English clients
  XIVSlothCombo/Data/ActionWatching.cs
Labels: Pull Request

#1024 [SAM] Added execute feature (dumping all Kenki into Shinten below target HP%)
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/SAM.cs
  XIVSlothCombo/Window/Functions/UserConfig.cs
Labels: Pull Request

#1013 [SCH] Heal Combos
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/SCH.cs
  XIVSlothCombo/Window/Functions/UserConfig.cs
Labels: Pull Request

#1030 Renormalized SCH & CustomComboPreset (Git Magic)
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/SCH.cs
Labels: Pull Request

#1029 Job Name Localization
  XIVSlothCombo/Attributes/CustomComboInfoAttribute.cs
  XIVSlothCombo/CustomCombo/Functions/Misc.cs
Labels: Pull Request

#1036 NIN uptime features added and fixed
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/NIN.cs
Labels: Pull Request

#1035 Jobname Localization Fixes
  XIVSlothCombo/Attributes/CustomComboInfoAttribute.cs
  XIVSlothCombo/CustomCombo/Functions/Misc.cs
  XIVSlothCombo/Window/Messages/Messages.cs
Labels: Pull Request

#1037 Adds option to remove frazzle from RDMPVP's burst mode.
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvP/RDMPVP.cs
Labels: Pull Request

#1033 [SCH] Heal combo fixes + internal naming parity
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/SCH.cs
  XIVSlothCombo/Window/Functions/UserConfig.cs
Labels: Pull Request, Beta

#1034 WHM AoE fixes
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/WHM.cs
Labels: Pull Request

#1039 [Healers] DoT Thresholds fixed and updated.
  XIVSlothCombo/Combos/PvE/AST.cs
  XIVSlothCombo/Combos/PvE/SCH.cs
  XIVSlothCombo/Combos/PvE/SGE.cs
  XIVSlothCombo/Combos/PvE/WHM.cs
  XIVSlothCombo/Window/Functions/UserConfig.cs
Labels: Pull Request, Beta

#1043 Changes to Healer DoT refresh timer sliders
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/AST.cs
  XIVSlothCombo/Combos/PvE/SCH.cs
  XIVSlothCombo/Combos/PvE/SGE.cs
  XIVSlothCombo/Combos/PvE/WHM.cs
  XIVSlothCombo/Window/Functions/UserConfig.cs
Labels: Pull Request

#1044 Ruin II's Bio feature fixed
  XIVSlothCombo/Combos/PvE/SCH.cs
Labels: Beta

#1049 Advanced DoT menus on AST/SGE/WHM
  XIVSlothCombo/Combos/CustomComboPreset.cs
  XIVSlothCombo/Combos/PvE/AST.cs
  XIVSlothCombo/Combos/PvE/SGE.cs
  XIVSlothCombo/Combos/PvE/WHM.cs
  XIVSlothCombo/Window/Functions/UserConfig.cs
Labels: Pull Request, Beta

#1054 Just fixed the Kardion buff ID.
  XIVSlothCombo/Combos/PvE/SGE.cs
Labels: Pull Request

#1068 [RPR] Regress null error fix
  XIVSlothCombo/Combos/PvE/RPR.cs
Labels: Pull Request
